import type { QuizQuestion, VivaQuestion } from "./types";

export const TOPICS = [
  "Numbers 1–20",
  "Addition 1–20",
  "Hindi Vocabulary",
  "Reading Comprehension",
  "Subtraction 1–20",
  "Shapes and Patterns",
];

export const LANGUAGES: string[] = ["Hindi", "Ho", "Mundari", "Santhali"];

export const QUESTION_TYPES = [
  "MCQ",
  "True/False",
  "Picture-based",
  "Oral/Voice",
  "Fill in the blank",
] as const;

export const DIFFICULTIES = ["Easy", "Medium", "Hard"] as const;

const TRANSLATION_PREFIX: Record<string, string> = {
  Hindi: "",
  Ho: "Ho: ",
  Mundari: "Mundari: ",
  Santhali: "Sat: ",
};

/**
 * Offline fallback translator used only when the real Sarvam-backed
 * `/api/translation` call is unavailable — see lesson-studio.tsx /
 * quiz-generator.tsx, which always try the real API first.
 */
export function mockTranslate(text: string, language: string): string {
  if (language === "Hindi") return text;
  return `${TRANSLATION_PREFIX[language] ?? ""}${text}`;
}

export interface GeneratedLesson {
  objectives: string[];
  teacherScript: string;
  motherTongueScript: string;
  activity: string;
}

export const CLASSES = ["Class 1", "Class 2", "Class 3", "Class 4", "Class 5"];
export const SUBJECTS = ["Mathematics", "Hindi", "Environmental Studies", "English"];
export const DURATIONS = ["20 minutes", "30 minutes", "40 minutes", "45 minutes"];

/**
 * Offline fallback lesson used only when the real AI lesson generation API
 * is unavailable — see lesson-studio.tsx, which always tries the real API
 * first and only falls back to this canned sample, clearly labeled as such
 * in the UI.
 */
export function generateMockLesson(
  studentLanguage: string,
  topic: string
): GeneratedLesson {
  return {
    objectives: [
      "Understand basic addition using real-world objects",
      "Add numbers confidently up to 20",
      "Apply addition to simple everyday word problems",
    ],
    teacherScript: TEACHER_LESSON_SCRIPT_HI,
    motherTongueScript:
      studentLanguage === "Santhali"
        ? STUDENT_LESSON_SCRIPT_SAT
        : `[${studentLanguage} translation of the ${topic} lesson script would appear here, generated by Sarvam AI.]`,
    activity:
      "Give each student 20 small stones or tamarind seeds. Ask them to form two groups — one with 3 stones and one with 2 stones — then count the total together. Repeat with sticks and other local objects, gradually increasing the numbers up to 20.",
  };
}

export const TEACHER_LESSON_SCRIPT_HI = `नमस्ते बच्चों! आज हम जोड़ना सीखेंगे। मान लीजिए मेरे पास तीन आम हैं। अगर मैं इसमें दो और आम मिला दूँ, तो मेरे पास कुल कितने आम होंगे? आइए गिनते हैं — एक, दो, तीन, चार, पाँच। तो तीन और दो मिलाकर पाँच होते हैं। अब अपनी स्लेट पर पत्थर या बीज रखकर खुद गिनने की कोशिश करें।`;

export const STUDENT_LESSON_SCRIPT_SAT = `Nomoskar Gidra'ko! Tehen'ge abo Add Koa Seko Lekhaye. Ne Tinag Am Menaghinge. Am Barea Sen Koa Add Lekhaye, Ontok Kotenag Am Menakoa? Bo Lekhta'be — Mit, Bar, Pe, Pon, Mon. Ontok Pe Ar Bar Ratge Mon Kanae. Nonde Am Sate Am Gada'renye Dul Ar Bir Lekhaye Kate Lekhta'be.`;

/**
 * Offline fallback question bank used only when the real AI Quiz
 * Generator API is unavailable — see quiz-generator.tsx.
 */
export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "q1",
    question: "3 + 4 = ?",
    type: "MCQ",
    options: ["5", "6", "7", "8"],
    correctAnswer: "7",
    difficulty: "Easy",
    competency: "Basic Addition",
  },
  {
    id: "q2",
    question: "If you have 8 mangoes and get 5 more, how many mangoes do you have?",
    type: "MCQ",
    options: ["12", "13", "14", "11"],
    correctAnswer: "13",
    difficulty: "Medium",
    competency: "Applied Addition",
  },
  {
    id: "q3",
    question: "10 + 10 = 20",
    type: "True/False",
    options: ["True", "False"],
    correctAnswer: "True",
    difficulty: "Easy",
    competency: "Basic Addition",
  },
  {
    id: "q4",
    question: "Count the stones shown and select the correct total.",
    type: "Picture-based",
    options: ["9", "10", "11", "12"],
    correctAnswer: "11",
    difficulty: "Medium",
    competency: "Counting",
  },
  {
    id: "q5",
    question: "Say the answer aloud: 6 + 6",
    type: "Oral/Voice",
    correctAnswer: "12",
    difficulty: "Medium",
    competency: "Mental Addition",
  },
  {
    id: "q6",
    question: "9 + ___ = 15",
    type: "Fill in the blank",
    correctAnswer: "6",
    difficulty: "Hard",
    competency: "Missing Addend",
  },
  {
    id: "q7",
    question: "Which number comes after 17?",
    type: "MCQ",
    options: ["16", "18", "19", "20"],
    correctAnswer: "18",
    difficulty: "Easy",
    competency: "Number Sequencing",
  },
  {
    id: "q8",
    question: "15 + 4 = ?",
    type: "MCQ",
    options: ["18", "19", "20", "17"],
    correctAnswer: "19",
    difficulty: "Medium",
    competency: "Two-digit Addition",
  },
  {
    id: "q9",
    question: "5 + 5 + 5 = 15",
    type: "True/False",
    options: ["True", "False"],
    correctAnswer: "True",
    difficulty: "Hard",
    competency: "Repeated Addition",
  },
  {
    id: "q10",
    question: "How many sticks in total? (bundle of 10 + 3 loose sticks)",
    type: "Picture-based",
    options: ["12", "13", "14", "10"],
    correctAnswer: "13",
    difficulty: "Easy",
    competency: "Place Value",
  },
];

/**
 * Offline fallback question bank used only when a real backend AI Viva
 * session can't be started — see viva-session.tsx.
 */
export const VIVA_QUESTIONS: VivaQuestion[] = [
  { id: "v1", question: "What is 3 + 2?", studentAnswer: "Five", isCorrect: true, competency: "Basic Addition" },
  { id: "v2", question: "What is 7 + 6?", studentAnswer: "Twelve", isCorrect: false, competency: "Two-digit Addition" },
  { id: "v3", question: "What comes after 14?", studentAnswer: "Fifteen", isCorrect: true, competency: "Number Sequencing" },
  { id: "v4", question: "If you have 4 stones and find 5 more, how many stones now?", studentAnswer: "Nine", isCorrect: true, competency: "Applied Addition" },
  { id: "v5", question: "What is 9 + 9?", studentAnswer: "Sixteen", isCorrect: false, competency: "Mental Addition" },
];
